import 'package:flutter_game/Domain/Models/animal_model.dart';

Game animalData = Game(
    id: 1,
    itemsName: [
      'الأسد',
      'الثعبان',
      'الفيل',
      'البطريق',
      'القطة',
      'الكلب',
      'الظرافة',
      'الصقر',
      'عصفورة',
      'بطة',
      'الحصان',
      'الفرخة',
      'الثعلب',
      'سمكة قرش',
      'الدولفن',
      'قرد',
      'بقرة',
      'معزة',
      'فهد',
      'كنغر',
      'غوريلا',
      'دب قطبي',
      'غراب',
      'نعامة',
      'غزالة',
      'خنزير',
      'السنجاب',
      'الجاموسة',
      'الذثب',
      'التمساح',
      'العنكبوت',
      'العقرب'
    ],
    categoryImage: 'assets/images/animals.jpg',
    categoryName: 'حيوانات');
Game foodData = Game(
    id: 2,
    itemsName: [
      'كشري',
      'محشي',
      'بليله',
      'مكرونه',
      'كبده',
      'جمبري',
      'سجق',
      'سوسيس',
      'حمام',
      'بانية',
      'بسلة',
      'ملوخية',
      'رز بلبن',
      'شاورما',
      'كوسة',
      'كوارع',
      'كنافة',
      'قطايف',
      'فراخ مشوية',
      'لوبيا',
      'سبانخ',
      'ورق عنب',
      'محشي كرنب',
      'فاصوليا',
      'جلاش',
    ],
    categoryImage: 'assets/images/food.jpg',
    categoryName: 'اكلات مصرية');
List<String> playersImages = [
  'assets/images/p1.png',
  'assets/images/p2.png',
  'assets/images/p3.png',
  'assets/images/p4.png',
  'assets/images/p5.png',
  'assets/images/p6.png',
  'assets/images/p7.png',
];
