import 'package:flutter_game/Domain/Models/AnimalModel.dart';

Animal animalData = Animal(
    id: 1,
    itemsName: [
      'الأسد',
      'الثعبان',
      'الفيل',
      'البطريق',
      'القطة',
      'الكلب',
      'الظرافة',
      'الصقر',
      'عصفورة',
      'بطة',
      'الحصان',
      'الفرخة',
      'الثعلب',
      'سمكة قرش',
      'الدولفن',
      'قرد',
      'بقرة',
      'معزة',
      'فهد',
      'كنغر',
      'غوريلا',
      'دب قطبي',
      'غراب',
      'نعامة',
      'غزالة',
      'خنزير',
      'السنجاب',
      'الجاموسة',
      'الذثب',
      'التمساح',
      'العنكبوت',
      'العقرب'
    ],
    categoryImage: 'assets/images/animals.jpg',
    categoryName: 'حيوانات');

List<String> playersImages = [
  'assets/images/p1.png',
  'assets/images/p2.png',
  'assets/images/p3.png',
  'assets/images/p4.png',
  'assets/images/p5.png',
  'assets/images/p6.png',
  'assets/images/p7.png',
];
